package model;

public class OraclePrepareCommands {
	//dept 
	public static final String ADD_DEPT = "INSERT INTO DEPT(ID,TITLE,DESCRIPTION) VALUES(getid(),?,?);";
	public static final String GET_ALL_DEPTS = "SELECT ID,TITLE,DESCRIPTION FROM DEPT;";
	public static final String GET_DEPTS_BY_ID = "SELECT ID,TITLE,DESCRIPTION FROM DEPT WHERE ID=?;";
	public static final String GET_DEPTS_BY_TITLE = "SELECT ID,TITLE,DESCRIPTION FROM DEPT WHERE TITLE=?;";
	public static final String REMOVE_DEPT = "DELETE FROM DEPT WHERE ID=?";
	public static final String UPDATE_DEPT = "UPDATE DEPT SET TITLE=?,DESCRIPTION=? where id=?;";
	//office
	public static final String ADD_OFFICE = "INSERT INTO OFFICE(ID,TITLE,ADDRESS,MANAGER) VALUES(getid(),?,?,?);";
	public static final String GET_ALL_OFFICES = "SELECT ID,TITLE,ADDRESS,MANAGER FROM OFFICE;";
	public static final String GET_OFFICE_BY_ID = "SELECT ID,TITLE,ADDRESS,MANAGER FROM OFFICE WHERE ID=?;";
	public static final String GET_OFFICE_BY_TITTLE = "SELECT ID,TITLE,ADDRESS,MANAGER FROM OFFICE WHERE TITLE=?;";
	public static final String REMOVE_OFFICE = "DELETE FROM OFFICE WHERE ID=?;";
	public static final String UPDATE_OFFICE = "UPDATE OFFICE SET TITLE=?,ADDRESS=?,MANAGER=? WHERE ID=?;";
	//worker
	public static final String ADD_WORKER = "INSERT INTO EMP(ID,FIRSTNAME,LASTNAME,MGRID,DEPARTMENT_ID,JOB_ID,OFFICE_ID,SALEGRADE) VALUES(getid(),?,?,?,?,?,?,?);";
	public static final String GET_ALL_WORKERS = "SELECT ID,FIRSTNAME,LASTNAME,MGRID,DEPARTMENT_ID,JOB_ID,OFFICE_ID,SALEGRADE FROM EMP;";
	public static final String GET_WORKER_BY_ID = "SELECT ID,FIRSTNAME,LASTNAME,MGRID,DEPARTMENT_ID,JOB_ID,OFFICE_ID,SALEGRADE FROM EMP WHERE ID=?;";
	public static final String GET_WORKER_BY_LAST_NAME = "SELECT ID,FIRSTNAME,LASTNAME,MGRID,DEPARTMENT_ID,JOB_ID,OFFICE_ID,SALEGRADE FROM EMP WHERE LASTNAME=?;";
	public static final String GET_WORKER_BY_MGR_ID = "SELECT ID,FIRSTNAME,LASTNAME,MGRID,DEPARTMENT_ID,JOB_ID,OFFICE_ID,SALEGRADE FROM EMP WHERE MGRID=?;";	
	public static final String REMOVE_WORKER = "DELETE FROM EMP WHERE ID=?;";
	public static final String UPDATE_WORKER = "UPDATE EMP SET FIRSTNAME=?,LASTNAME=?,MGRID=?,DEPARTMENT_ID=?,JOB_ID=?,OFFICE_ID=?,SALEGRADE=? WHERE ID=?;";
	//job
	public static final String ADD_JOB = "INSERT INTO JOBS(ID,TITLE,DESCRIPTION) VALUES(getid(),?,?);";
	public static final String GET_ALL_JOBS = "SELECT ID,TITLE,DESCRIPTION FROM JOBS;";
	public static final String GET_JOB_BY_ID = "SELECT ID,TITLE,DESCRIPTION FROM JOBS WHERE ID=?;";
	public static final String GET_JOB_BY_TITLE = "SELECT ID,TITLE,DESCRIPTION FROM JOBS WHERE TITLE=?;";
	public static final String REMOVE_JOB = "DELETE FROM JOBS WHERE ID=?;";
	public static final String UPDATE_JOB = "UPDATE JOBS SET TITLE=?,DESCRIPTION=? WHERE ID=?;";
}
