drop table EMPLOYEES;
drop table OFFICES;
drop table DEPARTMENTS;
drop table JOBS;
drop sequence counter;
create table EMPLOYEES (
	ID  NUMBER PRIMARY KEY NOT NULL,
	FIRSTNAME VARCHAR2(50),
	LASTNAME VARCHAR2(50),
	MGRID NUMBER(16),
	DEPARTMENT_ID NUMBER(16),
	JOB_ID NUMBER(16),
	OFFICE_ID NUMBER(16),
	SALEGRADE NUMBER(10,2)
);
 create index t_idx on EMPLOYEES(ID,FIRSTNAME,LASTNAME);
CREATE TABLE OFFICES (
	ID NUMBER(16) PRIMARY KEY NOT NULL,
	TITLE VARCHAR2(100),
	ADDRESS VARCHAR2(1000),
	MANAGER NUMBER(16)
);
CREATE TABLE JOBS (
	ID NUMBER PRIMARY KEY NOT NULL,
	TITLE VARCHAR2(300),
	DESCRIPTION VARCHAR2(1000)
);
CREATE TABLE DEPARTMENTS (
	ID NUMBER PRIMARY KEY NOT NULL,
	TITLE VARCHAR2(300),
	DESCRIPTION VARCHAR2(1000)
);
ALTER TABLE EMPLOYEES ADD CONSTRAINT ID_JOB FOREIGN KEY(JOB_ID) REFERENCES JOBS(ID);
ALTER TABLE EMPLOYEES ADD CONSTRAINT ID_DEP FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID);
ALTER TABLE EMPLOYEES ADD CONSTRAINT ID_LOC FOREIGN KEY(OFFICE_ID) REFERENCES OFFICES(ID);
CREATE SEQUENCE COUNTER 
  MINVALUE 1
  MAXVALUE 9999
  START WITH 1
  INCREMENT BY 1
  CYCLE;
CREATE OR REPLACE FUNCTION getid RETURN number is
  IDCHAR VARCHAR2(16);
BEGIN 
  SELECT TO_CHAR(SYSDATE,'yyyymmddSSSS')||TO_CHAR(COUNTER.NEXTVAL,'FM0000') into IDCHAR FROM dual;
  RETURN to_number(IDCHAR);
END getid;
/
SHOW ERROR